//! Direct implementation of file-system watching + debouncing (Phase B4,
//! `docs/06_Development_Roadmap.md`).
//!
//! This was first implemented with `notify-debouncer-mini` (the official companion
//! crate), then reverted after actually reproducing an **infinite indexing loop**: the
//! Linux inotify backend watches `OPEN`/`ATTRIB` (access/metadata-change) events by
//! default, and our indexing pipeline reading a file (computing a hash, extracting
//! text) itself generates an `OPEN` event.
//! `notify-debouncer-mini` doesn't pass along the event kind, so it became an infinite
//! loop of "read to index → that read generates an event → index again" (confirmed in
//! practice; see `WatchMask::ATTRIB | CREATE | OPEN | DELETE | CLOSE_WRITE | MODIFY |
//! MOVED_FROM | MOVED_TO` in the `notify` source).
//!
//! So we take the raw `notify::Event` directly and filter by `EventKind` — only
//! reacting to create/remove/actual content change (Data)/rename (Name), and ignoring
//! access (Access) and metadata changes (Metadata, e.g. atime) as noise generated by
//! our own reads.
//! Debouncing is implemented directly with a simple approach: "settle once no new event
//! has arrived for the same path for `debounce` after the first event."

use notify::event::ModifyKind;
use notify::{Config, Event, EventKind, RecommendedWatcher, RecursiveMode, Watcher};
use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::sync::mpsc::{channel, Receiver};
use std::time::Duration;

pub struct FileWatcher {
    // Watching stops when this is dropped, so it must be kept held.
    _watcher: RecommendedWatcher,
    raw_events: Receiver<Event>,
    debounce: Duration,
}

impl FileWatcher {
    /// Recursively watches under `root`. `debounce` is the time window of quiet after
    /// the last event required before a change is settled/confirmed.
    pub fn new(root: &Path, debounce: Duration) -> notify::Result<Self> {
        let (tx, raw_events) = channel();
        let mut watcher = RecommendedWatcher::new(
            move |res: notify::Result<Event>| {
                if let Ok(event) = res {
                    if is_relevant(&event.kind) {
                        let _ = tx.send(event);
                    }
                }
            },
            Config::default(),
        )?;
        watcher.watch(root, RecursiveMode::Recursive)?;
        Ok(Self {
            _watcher: watcher,
            raw_events,
            debounce,
        })
    }

    /// Blocks, waiting to receive one debounced list of changed paths. Returns `None`
    /// once watching ends (channel closed).
    pub fn recv(&self) -> Option<Vec<PathBuf>> {
        let first = self.raw_events.recv().ok()?;
        Some(self.settle(first))
    }

    /// Same as `recv`, but only waits for the first event up to `wait` — if nothing
    /// happens within that time, returns `None`. Used when you need to confirm "there
    /// are no more events" (e.g. the infinite re-indexing loop regression test).
    pub fn recv_timeout(&self, wait: Duration) -> Option<Vec<PathBuf>> {
        let first = self.raw_events.recv_timeout(wait).ok()?;
        Some(self.settle(first))
    }

    /// After the first event already received, keeps collecting new events for the
    /// same paths until things go quiet (`debounce`).
    fn settle(&self, first: Event) -> Vec<PathBuf> {
        let mut pending: HashSet<PathBuf> = first.paths.into_iter().collect();
        while let Ok(event) = self.raw_events.recv_timeout(self.debounce) {
            pending.extend(event.paths);
        }
        pending.into_iter().collect()
    }
}

/// Keeps only the event kinds we actually need to react to. `Access` (open/close) and
/// `Modify(Metadata)` (atime, etc.) are excluded as noise generated by the indexing
/// pipeline's own reads.
fn is_relevant(kind: &EventKind) -> bool {
    matches!(
        kind,
        EventKind::Create(_)
            | EventKind::Remove(_)
            | EventKind::Modify(ModifyKind::Data(_) | ModifyKind::Name(_))
    )
}
